version: "3.9"
services:
  customer-service:
    build: ./customer-service
    ports:
      - "8090:8090"
    environment:
      - ENV=production

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    environment:
      - ENV=production
    depends_on:
      - customer-service
