# docker-compose.yml
version: '3.9'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: fleetadmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartfleet
    ports:
      - "5432:5432"

  telemetry-service:
    build: ./telemetry-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - redis

  analytics-service:
    build: ./analytics-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - postgres

  notification-service:
    build: ./notification-service
    ports:
      - "8083:8083"
    depends_on:
      - redis

  simulator-service:
    build: ./simulator-service
    ports:
      - "8084:8084"
    depends_on:
      - kafka


